relationship_tarot_cards = {
    "The Fool": "You are going through a new beginning in love, filled with excitement but also uncertainty. Embrace the journey with an open heart, but don’t ignore red flags.",
    "The Magician": "You are going through a phase of empowerment in your relationships, where your words and actions shape your reality. Use your skills to communicate effectively and manifest the connection you desire.",
    "The High Priestess": "You are going through a period where intuition and hidden truths play a major role. Trust your instincts and observe before making decisions, some answers lie beneath the surface.",
    "The Empress": "You are going through a time of nurturing and emotional growth in love. Express love openly, but also allow yourself to receive it in return. Prioritize self-care in your relationships.",
    "The Emperor": "You are going through a phase where structure and stability are important in your relationship. Take charge of your emotional boundaries and establish a solid foundation based on mutual respect.",
    "The Hierophant": "You are going through a time where tradition, commitment, or shared values are in focus. Seek wisdom in your connections and ensure that your beliefs align with your partner’s for long-term harmony.",
    "The Lovers": "You are going through a moment of deep emotional connection or an important choice in love. Follow your heart, but make sure passion aligns with compatibility and shared goals.",
    "The Chariot": "You are going through a phase where control and direction are key in your relationship. Take the reins; be clear about your intentions and ensure both partners are moving in the same direction.",
    "Strength": "You are going through a test of patience, compassion, or inner resilience in love. Approach your relationships with gentle strength; overcoming challenges with kindness will bring deeper trust.",
    "The Hermit": "You are going through a period of self-reflection and introspection in love. Take time to understand your emotional needs before seeking fulfilment in others. Solitude can bring clarity.",
    "Wheel of Fortune": "You are going through a cycle of change and unpredictability in your relationship. Embrace the ups and downs; what is meant for you will stay, and what isn’t will make room for something better.",
    "Justice": "You are going through a phase where fairness, truth, and accountability are essential. Be honest with yourself and others; balance between giving and receiving is necessary for a healthy relationship.",
    "The Hanged Man": "You are going through a period of pause or stagnation in your love life. Shift your perspective; sometimes stepping back can bring new insights and a better understanding of what you truly want.",
    "Death": "You are going through a transformation in love - an ending or a major shift. Let go of what no longer serves you; endings create space for new beginnings and deeper connections.",
    "Temperance": "You are going through a time that requires balance and patience in love. Don’t rush; allow things to develop naturally. Emotional harmony will bring stronger bonds.",
    "The Devil": "You are going through a phase of temptation, attachment, or unhealthy patterns in love. Recognize what is holding you back, whether it’s fear, control, or toxicity, and work on breaking free.",
    "The Tower": "You are going through a sudden change or revelation in your relationship. Though unsettling, this shift is necessary for truth and growth. Embrace the change and rebuild with clarity.",
    "The Star": "You are going through a healing phase in love, where hope is being restored. Trust in the process, stay optimistic, and your heart will guide you toward deeper, more fulfilling connections.",
    "The Moon": "You are going through a time of confusion, uncertainty, or hidden emotions in love. Listen to your intuition, but avoid making assumptions. Clarity will come with time and open communication.",
    "The Sun": "You are going through a period of joy, clarity, and emotional warmth in love. Celebrate love in all its forms; share your happiness openly and enjoy the positive energy surrounding you.",
    "Judgment": "You are going through a moment of self-realization or an important decision in love. Reflect on past experiences, learn from them, and move forward with a clearer vision of what you truly need.",
    "The World": "You are going through a phase of completion and fulfillment in your relationships. Enjoy the wholeness you feel; whether alone or with someone, you are exactly where you need to be."}

decision_making_tarot_cards = {
    "The Fool": "You are going through a phase where spontaneity and new opportunities are influencing your decision-making. Take the leap, but be mindful of the risks before committing to a path.",
    "The Magician": "You are going through a time where you have all the resources and skills needed to make a confident choice. Trust your abilities and take action with clarity and intention.",
    "The High Priestess": "You are going through a period where intuition and subconscious insights play a key role in your decisions. Listen to your inner voice and allow time for answers to reveal themselves.",
    "The Empress": "You are going through a time where nurturing and patience are needed in your choices. Allow things to develop naturally and make decisions that support growth and harmony.",
    "The Emperor": "You are going through a phase where structure and control are necessary in your decision-making. Be firm in your choices and establish a clear plan to move forward.",
    "The Hierophant": "You are going through a time where tradition, wisdom, or external guidance influence your choices. Seek advice from experienced sources but ensure your decision aligns with your values.",
    "The Lovers": "You are going through a moment where an important choice requires alignment between heart and mind. Weigh your options carefully and ensure your decision is based on genuine connection and purpose.",
    "The Chariot": "You are going through a phase where determination and willpower are essential in making a decision. Stay focused and take control of the situation to ensure a victorious outcome.",
    "Strength": "You are going through a time where patience and inner resilience are required to make a wise choice. Approach decisions with confidence and self-control rather than acting on impulse.",
    "The Hermit": "You are going through a period of deep self-reflection regarding an important decision. Take time to retreat, gather wisdom, and trust that clarity will come with introspection.",
    "Wheel of Fortune": "You are going through a cycle of unpredictability where external forces may influence your decision. Adapt to changes and trust that the right path will unfold naturally.",
    "Justice": "You are going through a time where fairness, truth, and logic must guide your choice. Consider all facts objectively and ensure your decision is aligned with integrity.",
    "The Hanged Man": "You are going through a moment where patience and a new perspective are needed before deciding. Take a step back and see the situation from a different angle before moving forward.",
    "Death": "You are going through a transformative period where letting go is necessary to make room for new opportunities. Release what no longer serves you and embrace change as a path to growth.",
    "Temperance": "You are going through a time where balance and moderation are key to making the right choice. Do not rush into a decision and seek harmony between logic and emotion.",
    "The Devil": "You are going through a phase where fear, attachment, or unhealthy patterns may be clouding your judgment. Recognize what is limiting you and make a choice that leads to freedom and empowerment.",
    "The Tower": "You are going through a moment of sudden change or realization that impacts your decision-making. Accept the shift and rebuild with clarity rather than resisting necessary change.",
    "The Star": "You are going through a time where hope and inspiration should guide your choices. Trust in a positive outcome and let optimism lead you toward the right path.",
    "The Moon": "You are going through a phase of uncertainty where illusions or hidden truths may affect your decision. Avoid acting impulsively and seek clarity before committing to a choice.",
    "The Sun": "You are going through a period of clarity and confidence in your decision-making. Trust in your path and move forward with enthusiasm and certainty.",
    "Judgment": "You are going through a moment of self-realization where past experiences shape your choice. Reflect on what you have learned and make a decision that aligns with your true purpose.",
    "The World": "You are going through a phase of completion where a major decision leads to fulfillment. Embrace the final step with confidence, knowing that everything is coming together as it should."}

personal_growth_tarot_cards = {
    "The Fool": "This is your time of self-discovery. You’re learning to trust yourself and embrace new experiences. Keep an open mind and heart, but also be mindful of the lessons life is teaching you.",
    "The Magician": "You’re realizing your personal power and ability to shape your reality. Stay focused on your goals and use your talents wisely.",
    "The High Priestess": "A time of deep self-reflection and spiritual insight. Seek wisdom in silence and trust the process. Meditation or a calm activity can be a good idea to reach deeper thoughts about yourself.",
    "The Empress": "You are embracing self-love and stepping into your power. Take care of your physical and emotional well-being. Now is the time to put some focus on physical activities and see faster results. It is also a time for you to be careful with your health.",
    "The Emperor": "You are stepping into leadership and responsibility. Beware of the following events in your life because you will need to show your responsible side. Stand firm in your principles but remain adaptable.",
    "The Hierophant": "You’re developing a deeper understanding of spiritual or societal beliefs. Seek knowledge and stay true to your principles.",
    "The Lovers": "You are aligning with your true self. The real you is becoming stronger. Seek balance in relationships and within yourself.",
    "The Chariot": "You are learning how to harness your willpower and stay disciplined in your journey. Focus on self-control and perseverance. Victory comes from staying the course.",
    "Strength": "You are developing resilience, emotional intelligence, and personal power. Approach challenges with calmness and confidence rather than aggression.",
    "The Hermit": "A time of deep spiritual growth and self-discovery. Seek solitude, meditate, and listen to your inner wisdom.",
    "Wheel of Fortune": "Sometimes it is hard, but you’re learning to accept life’s ups and downs. Adaptability is key. Ride the waves of change with faith.",
    "Justice": "New lessons in life… You are learning about integrity and responsibility. Live in alignment with your values and moral principles.",
    "The Hanged Man": "Breathe… You are learning patience and surrendering control. Release the need for immediate results—trust the process.",
    "Death": "ATTENTION: This card has a strong name, but in personal growth, it means a powerful transformation is happening in your life. Release old patterns to welcome new growth.",
    "Temperance": "You are learning to manage emotions and create inner peace. Stay centered and embrace harmony.",
    "The Devil": "You are confronting your inner fears, bad habits, or limiting beliefs. Acknowledge what’s holding you back and work towards self-liberation.",
    "The Tower": "A powerful transformation is taking place, shattering old illusions. Let go of false beliefs and allow yourself to rebuild stronger.",
    "The Star": "You are stepping into your light, full of inspiration and confidence. Trust yourself and embrace optimism.",
    "The Moon": "You are exploring your subconscious and facing fears. Embrace your intuition and trust your inner guidance.",
    "The Sun": "A period of self-discovery and happiness. Enjoy your success and let your light shine.",
    "Judgment": "A time of deep healing, forgiveness, and self-acceptance. Release past guilt and step into a renewed sense of self.",
    "The World": "A time of achievement and spiritual growth. Recognize how far you’ve come and embrace your full potential."}

future_tarot_cards = {
    "The Fool": "A new adventure is beginning, full of possibilities. Embrace the unknown, but proceed with awareness.",
    "The Magician": "You are in control of what happens next. Take initiative; the universe supports your efforts.",
    "The High Priestess": "Things are not yet revealed, but answers will come in time. Be patient and trust that clarity will unfold.",
    "The Empress": "Abundance and creativity are on the way. Nurture what matters to you, and watch it flourish.",
    "The Emperor": "A stable and structured future awaits. Take control and plan ahead.",
    "The Hierophant": "A future shaped by tradition and moral values. Stay true to what you believe in.",
    "The Lovers": "A strong relationship or choice that defines your path. Advice: Choose love and authenticity.",
    "The Chariot": "A period of success and progress lies ahead. Keep your eyes on your goals and don’t let distractions derail you.",
    "Strength": "A period of inner strength and perseverance will shape your future. Stay patient and trust in your own power.",
    "The Hermit": "A journey of wisdom and enlightenment awaits. Take your time; everything will become clear in due time.",
    "Wheel of Fortune": "Big changes are ahead—expect the unexpected. Stay flexible and open to new opportunities.",
    "Justice": "Justice will be served—karma is at play. If you do something negative, you will receive something negative back. If you do something positive… wait for the best. Stay honest, and the right outcome will follow.",
    "The Hanged Man": "A delay or pause is necessary before moving forward. Use this time for reflection and growth.",
    "Death": "A major life change is approaching. Trust that this transformation will lead to renewal.",
    "Temperance": "A period of peace and stability is ahead. Stay patient and trust in the flow of life.",
    "The Devil": "If left unchecked, unhealthy patterns may continue. Recognize harmful influences and take control of your destiny.",
    "The Tower": "A major upheaval may be coming, but it will lead to a fresh start. This fresh start is what will lead to your biggest achievement. Stay resilient—this storm will pass, and clarity will follow.",
    "The Star": "A bright and promising future awaits. Stay hopeful and follow your dreams.",
    "The Moon": "The path ahead is unclear, and illusions may be present. Take your time and let the truth reveal itself naturally.",
    "The Sun": "A bright and prosperous future is ahead. Stay positive and embrace life’s opportunities.",
    "Judgment": "A moment of reckoning and transformation is coming. Be open to change and trust in your personal growth.",
    "The World": "A successful and fulfilling future is within reach. Celebrate your victories and prepare for new beginnings."}