cards = {
    "The Fool": "You are going through a phase where spontaneity and new opportunities are influencing your decision-making. Take the leap, but be mindful of the risks before committing to a path.",
    "The Magician": "You are going through a time where you have all the resources and skills needed to make a confident choice. Trust your abilities and take action with clarity and intention.",
    "The High Priestess": "You are going through a period where intuition and subconscious insights play a key role in your decisions. Listen to your inner voice and allow time for answers to reveal themselves.",
    "The Empress": "You are going through a time where nurturing and patience are needed in your choices. Allow things to develop naturally and make decisions that support growth and harmony.",
    "The Emperor": "You are going through a phase where structure and control are necessary in your decision-making. Be firm in your choices and establish a clear plan to move forward.",
    "The Hierophant": "You are going through a time where tradition, wisdom, or external guidance influence your choices. Seek advice from experienced sources but ensure your decision aligns with your values.",
    "The Lovers": "You are going through a moment where an important choice requires alignment between heart and mind. Weigh your options carefully and ensure your decision is based on genuine connection and purpose.",
    "The Chariot": "You are going through a phase where determination and willpower are essential in making a decision. Stay focused and take control of the situation to ensure a victorious outcome.",
    "Strength": "You are going through a time where patience and inner resilience are required to make a wise choice. Approach decisions with confidence and self-control rather than acting on impulse.",
    "The Hermit": "You are going through a period of deep self-reflection regarding an important decision. Take time to retreat, gather wisdom, and trust that clarity will come with introspection.",
    "Wheel of Fortune": "You are going through a cycle of unpredictability where external forces may influence your decision. Adapt to changes and trust that the right path will unfold naturally.",
    "Justice": "You are going through a time where fairness, truth, and logic must guide your choice. Consider all facts objectively and ensure your decision is aligned with integrity.",
    "The Hanged Man": "You are going through a moment where patience and a new perspective are needed before deciding. Take a step back and see the situation from a different angle before moving forward.",
    "Death": "You are going through a transformative period where letting go is necessary to make room for new opportunities. Release what no longer serves you and embrace change as a path to growth.",
    "Temperance": "You are going through a time where balance and moderation are key to making the right choice. Do not rush into a decision and seek harmony between logic and emotion.",
    "The Devil": "You are going through a phase where fear, attachment, or unhealthy patterns may be clouding your judgment. Recognize what is limiting you and make a choice that leads to freedom and empowerment.",
    "The Tower": "You are going through a moment of sudden change or realization that impacts your decision-making. Accept the shift and rebuild with clarity rather than resisting necessary change.",
    "The Star": "You are going through a time where hope and inspiration should guide your choices. Trust in a positive outcome and let optimism lead you toward the right path.",
    "The Moon": "You are going through a phase of uncertainty where illusions or hidden truths may affect your decision. Avoid acting impulsively and seek clarity before committing to a choice.",
    "The Sun": "You are going through a period of clarity and confidence in your decision-making. Trust in your path and move forward with enthusiasm and certainty.",
    "Judgment": "You are going through a moment of self-realization where past experiences shape your choice. Reflect on what you have learned and make a decision that aligns with your true purpose.",
    "The World": "You are going through a phase of completion where a major decision leads to fulfillment. Embrace the final step with confidence, knowing that everything is coming together as it should."}
