cards = {
    "The Fool": "A new adventure is beginning, full of possibilities. Embrace the unknown, but proceed with awareness.",
    "The Magician": "You are in control of what happens next. Take initiative; the universe supports your efforts.",
    "The High Priestess": "Things are not yet revealed, but answers will come in time. Be patient and trust that clarity will unfold.",
    "The Empress": "Abundance and creativity are on the way. Nurture what matters to you, and watch it flourish.",
    "The Emperor": "A stable and structured future awaits. Take control and plan ahead.",
    "The Hierophant": "A future shaped by tradition and moral values. Stay true to what you believe in.",
    "The Lovers": "A strong relationship or choice that defines your path. Advice: Choose love and authenticity.",
    "The Chariot": "A period of success and progress lies ahead. Keep your eyes on your goals and don’t let distractions derail you.",
    "Strength": "A period of inner strength and perseverance will shape your future. Stay patient and trust in your own power.",
    "The Hermit": "A journey of wisdom and enlightenment awaits. Take your time; everything will become clear in due time.",
    "Wheel of Fortune": "Big changes are ahead—expect the unexpected. Stay flexible and open to new opportunities.",
    "Justice": "Justice will be served—karma is at play. If you do something negative, you will receive something negative back. If you do something positive… wait for the best. Stay honest, and the right outcome will follow.",
    "The Hanged Man": "A delay or pause is necessary before moving forward. Use this time for reflection and growth.",
    "Death": "A major life change is approaching. Trust that this transformation will lead to renewal.",
    "Temperance": "A period of peace and stability is ahead. Stay patient and trust in the flow of life.",
    "The Devil": "If left unchecked, unhealthy patterns may continue. Recognize harmful influences and take control of your destiny.",
    "The Tower": "A major upheaval may be coming, but it will lead to a fresh start. This fresh start is what will lead to your biggest achievement. Stay resilient—this storm will pass, and clarity will follow.",
    "The Star": "A bright and promising future awaits. Stay hopeful and follow your dreams.",
    "The Moon": "The path ahead is unclear, and illusions may be present. Take your time and let the truth reveal itself naturally.",
    "The Sun": "A bright and prosperous future is ahead. Stay positive and embrace life’s opportunities.",
    "Judgment": "A moment of reckoning and transformation is coming. Be open to change and trust in your personal growth.",
    "The World": "A successful and fulfilling future is within reach. Celebrate your victories and prepare for new beginnings."}