personal_growth_tarot_cards = {
    "The Fool": "This is your time of self-discovery. You’re learning to trust yourself and embrace new experiences. Keep an open mind and heart, but also be mindful of the lessons life is teaching you.",
    "The Magician": "You’re realizing your personal power and ability to shape your reality. Stay focused on your goals and use your talents wisely.",
    "The High Priestess": "A time of deep self-reflection and spiritual insight. Seek wisdom in silence and trust the process. Meditation or a calm activity can be a good idea to reach deeper thoughts about yourself.",
    "The Empress": "You are embracing self-love and stepping into your power. Take care of your physical and emotional well-being. Now is the time to put some focus on physical activities and see faster results. It is also a time for you to be careful with your health.",
    "The Emperor": "You are stepping into leadership and responsibility. Beware of the following events in your life because you will need to show your responsible side. Stand firm in your principles but remain adaptable.",
    "The Hierophant": "You’re developing a deeper understanding of spiritual or societal beliefs. Seek knowledge and stay true to your principles.",
    "The Lovers": "You are aligning with your true self. The real you is becoming stronger. Seek balance in relationships and within yourself.",
    "The Chariot": "You are learning how to harness your willpower and stay disciplined in your journey. Focus on self-control and perseverance. Victory comes from staying the course.",
    "Strength": "You are developing resilience, emotional intelligence, and personal power. Approach challenges with calmness and confidence rather than aggression.",
    "The Hermit": "A time of deep spiritual growth and self-discovery. Seek solitude, meditate, and listen to your inner wisdom.",
    "Wheel of Fortune": "Sometimes it is hard, but you’re learning to accept life’s ups and downs. Adaptability is key. Ride the waves of change with faith.",
    "Justice": "New lessons in life… You are learning about integrity and responsibility. Live in alignment with your values and moral principles.",
    "The Hanged Man": "Breathe… You are learning patience and surrendering control. Release the need for immediate results—trust the process.",
    "Death": "ATTENTION: This card has a strong name, but in personal growth, it means a powerful transformation is happening in your life. Release old patterns to welcome new growth.",
    "Temperance": "You are learning to manage emotions and create inner peace. Stay centered and embrace harmony.",
    "The Devil": "You are confronting your inner fears, bad habits, or limiting beliefs. Acknowledge what’s holding you back and work towards self-liberation.",
    "The Tower": "A powerful transformation is taking place, shattering old illusions. Let go of false beliefs and allow yourself to rebuild stronger.",
    "The Star": "You are stepping into your light, full of inspiration and confidence. Trust yourself and embrace optimism.",
    "The Moon": "You are exploring your subconscious and facing fears. Embrace your intuition and trust your inner guidance.",
    "The Sun": "A period of self-discovery and happiness. Enjoy your success and let your light shine.",
    "Judgment": "A time of deep healing, forgiveness, and self-acceptance. Release past guilt and step into a renewed sense of self.",
    "The World": "A time of achievement and spiritual growth. Recognize how far you’ve come and embrace your full potential."}
